In [1]:
#Q2. Row Echelon Form: Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations. 


In [10]:
import numpy as np
A = np.random.randint(0, 10, (5, 5))
print("Matrix A:")
print(A)
A = A.astype(float)
rows, cols = A.shape
for r in range(rows):
    pivot = A[r, r]
    if pivot != 0:
        A[r] = A[r] / pivot
    for r2 in range(r + 1, rows):
        multiplier = A[r2, r]
        A[r2] = A[r2] - multiplier * A[r]

print("\nRow Echelon Form of Matrix A:")
print(A)


Matrix A:
[[3 9 8 0 7]
 [1 9 4 2 1]
 [9 7 6 0 7]
 [0 3 6 7 3]
 [3 5 7 4 7]]

Row Echelon Form of Matrix A:
[[ 1.          3.          2.66666667  0.          2.33333333]
 [ 0.          1.          0.22222222  0.33333333 -0.22222222]
 [-0.         -0.          1.         -0.49180328  1.36065574]
 [ 0.          0.          0.          1.         -0.41634981]
 [ 0.          0.          0.          0.          1.        ]]


In [14]:
import numpy as np
import scipy.linalg as la

# Perform Singular Value Decomposition on matrix A
U, S, V = la.svd(A)

# Separate and print matrices U, Σ, and V
print("Matrix U:\n", U)
print("\nSingular Values Σ:\n", S)
print("\nMatrix V:\n", V)

# Verify that A equals the product of U, Σ, and V
A_approximated = np.dot(U, np.dot(np.diag(S), V))
print("\nApproximated Matrix A:\n", A_approximated)

# Check if A equals the product of U, Σ, and V
print("\nIs A equal to the product of U, Σ, and V?", np.allclose(A, A_approximated))

# Find the rank 2 and rank 3 approximations of matrix A
U_rank2 = U[:, :2]
S_rank2 = np.diag(S[:2])
V_rank2 = V[:2, :]

U_rank3 = U[:, :3]
S_rank3 = np.diag(S[:3])
V_rank3 = V[:3, :]

# Print the rank 2 and rank 3 approximations of matrix A
print("\nRank 2 Approximation:\n", np.dot(U_rank2, np.dot(S_rank2, V_rank2)))
print("\nRank 3 Approximation:\n", np.dot(U_rank3, np.dot(S_rank3, V_rank3)))

Matrix U:
 [[ 0.95012915 -0.17661052  0.04087731 -0.00989703 -0.25356346]
 [ 0.11881334 -0.49893237  0.15873012  0.23944494  0.80896276]
 [ 0.26270089  0.63710567 -0.19168111 -0.45823744  0.52759966]
 [-0.05043818 -0.43785174 -0.84821019 -0.29358926 -0.0093091 ]
 [ 0.10762075  0.34965329 -0.46575918  0.80398505  0.05326132]]

Singular Values Σ:
 [4.98707908 1.77176691 0.82017742 0.53067431 0.26002271]

Matrix V:
 [[ 0.19051816  0.59537872  0.56601901 -0.02807874  0.53671321]
 [-0.09968045 -0.58064293  0.03119509 -0.5178408   0.61950413]
 [ 0.04983959  0.34305021 -0.05779432 -0.85473062 -0.38200516]
 [-0.01864991  0.39525912 -0.81296478  0.02183713  0.42665422]
 [-0.97515888  0.18564682  0.1199893   0.00334551  0.01384915]]

Approximated Matrix A:
 [[ 1.00000000e+00  3.00000000e+00  2.66666667e+00  4.31512465e-17
   2.33333333e+00]
 [ 2.77555756e-17  1.00000000e+00  2.22222222e-01  3.33333333e-01
  -2.22222222e-01]
 [-5.55111512e-17 -3.29597460e-16  1.00000000e+00 -4.91803279e-01
   1.3